"""데모 모드용 샘플 이메일. 실제 Gmail 연동 없이 앱 동작을 바로 확인할 수 있다."""

from app.schemas import EmailMessage

DEMO_EMAILS: list[EmailMessage] = [
    EmailMessage(
        id="d1",
        thread_id="t1",
        sender="noreply@toss.im",
        subject="[토스] 결제 완료 안내 - 11,000원",
        snippet="고객님의 카드가 정상적으로 결제되었습니다. 주문 내역을 확인하세요.",
        date="2026-06-25T09:12:00+09:00",
    ),
    EmailMessage(
        id="d2",
        thread_id="t2",
        sender="receipts@paypal.com",
        subject="Your payment receipt from PayPal",
        snippet="You sent a payment of $42.00 USD. This is your receipt.",
        date="2026-06-24T22:01:00+09:00",
    ),
    EmailMessage(
        id="d3",
        thread_id="t3",
        sender="news@stratechery.com",
        subject="Weekly digest: AI 업계 이번주 소식",
        snippet="이번 주 뉴스레터에서는 AI 업계 동향을 정리했습니다. 구독을 해지하려면 하단을 클릭하세요.",
        date="2026-06-23T07:00:00+09:00",
        has_list_unsubscribe=True,
    ),
    EmailMessage(
        id="d4",
        thread_id="t4",
        sender="hello@substack.com",
        subject="Newsletter: This week in tech",
        snippet="Here's our weekly digest of the best tech writing on the web.",
        date="2026-06-22T08:30:00+09:00",
        has_list_unsubscribe=True,
    ),
    EmailMessage(
        id="d5",
        thread_id="t5",
        sender="deals@coupang.com",
        subject="오늘만 특가! 전상품 30% 할인 + 무료배송",
        snippet="놓치면 후회하는 한정수량 이벤트, 지금 바로 쿠폰 받아가세요.",
        date="2026-06-26T11:00:00+09:00",
    ),
    EmailMessage(
        id="d6",
        thread_id="t6",
        sender="promo@oliveyoung.co.kr",
        subject="BLACK FRIDAY SALE - Up to 50% off",
        snippet="Limited time deal! Use code SAVE50 for free shipping.",
        date="2026-06-21T15:40:00+09:00",
    ),
    EmailMessage(
        id="d7",
        thread_id="t7",
        sender="notifications@github.com",
        subject="[bll3479/AX_automatization_miniproject] New pull request review requested",
        snippet="A code review is requested on PR #12 before the deadline tomorrow.",
        date="2026-06-27T13:05:00+09:00",
    ),
    EmailMessage(
        id="d8",
        thread_id="t8",
        sender="calendar-notification@google.com",
        subject="회의 알림: 주간보고 미팅",
        snippet="내일 오전 10시 회의 일정이 있습니다. Calendar invite가 첨부되어 있습니다.",
        date="2026-06-27T18:00:00+09:00",
    ),
    EmailMessage(
        id="d9",
        thread_id="t9",
        sender="security-noreply@accounts.google.com",
        subject="[Google] 로그인 알림: 새 기기에서 로그인",
        snippet="새 기기에서 로그인 시도가 감지되었습니다. 본인이 아니라면 비밀번호를 재설정하세요.",
        date="2026-06-28T01:20:00+09:00",
    ),
    EmailMessage(
        id="d10",
        thread_id="t10",
        sender="no-reply@accounts.kakao.com",
        subject="[카카오] 인증번호는 [482913] 입니다",
        snippet="본인확인을 위해 인증번호를 입력해주세요. 타인에게 절대 알리지 마세요.",
        date="2026-06-28T08:45:00+09:00",
    ),
    EmailMessage(
        id="d11",
        thread_id="t11",
        sender="사람인 <noreply@saramin.co.kr>",
        subject="[사람인] 백엔드 개발자 신입 공고 - 지원 마감 D-3",
        snippet="입사지원하신 포지션의 서류 검토가 시작되었습니다. 신입 채용 공고를 확인하세요.",
        date="2026-06-20T09:00:00+09:00",
    ),
    EmailMessage(
        id="d12",
        thread_id="t12",
        sender="인크루트 <mail@incruit.com>",
        subject="[인크루트] 회원님 맞춤 채용 공고 도착",
        snippet="회원님의 스펙에 맞는 신입 공고가 새로 등록되었습니다. 지금 바로 입사지원 해보세요.",
        date="2026-06-19T10:30:00+09:00",
    ),
    EmailMessage(
        id="d13",
        thread_id="t13",
        sender="minji.kim@company.com",
        subject="다음주 점심 약속 어떠세요?",
        snippet="오랜만이에요! 다음 주에 시간 괜찮으시면 점심 같이 해요.",
        date="2026-06-20T12:15:00+09:00",
    ),
    EmailMessage(
        id="d14",
        thread_id="t14",
        sender="updates@randomservice.io",
        subject="서비스 점검 안내",
        snippet="6월 30일 새벽 시스템 점검이 예정되어 있습니다.",
        date="2026-06-19T10:00:00+09:00",
    ),
]
